#Last change:
#Wed May 10 00:21:31 MSK 2023
dot_31.pixels=0
dot_19.y=0
dot_19.x=0
connect_23_to=0
dot_19.s=0
dot_15.y=0
dot_19.p=0
dot_15.x=0
dot_15.s=0
dot_11.y=0
dot_15.p=0
dot_11.x=0
connect_19_to=0
dot_9.y=0
window_x_9=0
dot_9.x=0
dot_17.pixels=0
window_x_8=0
window_x_7=0
window_x_6=0
dot_11.s=0
window_x_5=0
window_x_4=0
dot_9.s=0
window_x_3=0
dot_11.p=0
window_x_2=0
window_x_1=1
dot_5.y=0
dot_9.p=0
dot_7.pixels=0
dot_5.x=0
dot_xels_17.p=0
dot_5.s=0
dot_1.y=0
dot_5.p=0
dot_1.x=0
border_x_16=0
border_x_15=0
dot_40.pixels=0
border_x_14=0
dot_xels_13.p=0
dot_1.s=1
border_x_13=0
border_x_12=0
border_x_11=0
dot_1.p=200
border_x_10=0
connect_13_to=0
connect_4_to=0
dot_36.y=0
dot_36.x=0
dot_34.pixels=0
dot_36.s=0
dot_26.pixels=0
dot_32.y=0
dot_36.p=0
dot_32.x=0
connect_34_to=0
dot_32.s=0
dot_32.p=0
dot_xels_38.p=0
dot_xels_34.p=0
window_line_color=\#FFFFFF
dot_xels_30.p=0
dot_35.pixels=0
dot_11.pixels=0
dot_29.y=0
dot_29.x=0
connect_24_to=0
dot_xels_9.p=0
dot_1.pixels=100
dot_29.s=0
dot_25.y=0
dot_29.p=0
dot_25.x=0
dot_xels_5.p=0
dot_25.s=0
dot_21.y=0
dot_25.p=0
dot_21.x=0
dot_xels_1.p=100
dot_21.s=0
dot_21.p=0
dot_xels_27.p=0
border_y_9=0
border_y_8=0
border_y_16=0
dot_20.pixels=0
border_y_7=0
border_y_15=0
border_y_6=480
border_y_14=0
dot_xels_23.p=0
border_y_5=480
border_y_13=0
border_y_4=240
border_y_12=0
border_y_11=0
border_y_3=40
border_y_10=0
border_y_2=40
border_y_1=240
connect_14_to=0
connect_5_to=0
dot_38.pixels=0
connect_35_to=0
dot_18.y=0
dot_4.pixels=0
dot_18.x=0
dot_18.s=0
dot_14.y=0
dot_18.p=0
dot_14.x=0
dot_14.s=0
dot_10.y=0
dot_14.p=0
dot_10.x=0
window_height=500
dot_8.y=0
dot_8.x=0
dot_10.s=0
dot_8.s=0
dot_10.p=0
dot_4.y=0
dot_8.p=0
dot_4.x=0
dot_xels_40.p=0
dot_xels_16.p=0
dot_4.s=0
dot_23.pixels=0
dot_4.p=0
dot_15.pixels=0
dot_xels_12.p=0
dot_39.y=0
dot_39.x=0
connect_25_to=0
dot_n_2.pixels=442
dot_39.s=0
dot_35.y=0
dot_39.p=0
dot_35.x=0
dot_35.s=0
dot_31.y=0
dot_35.p=0
dot_31.x=0
dot_31.s=0
dot_31.p=0
dot_32.pixels=0
dot_24.pixels=0
dot_xels_37.p=0
dot_xels_33.p=0
connect_40_to=0
connect_15_to=0
connect_6_to=0
dot_18.pixels=0
dot_8.pixels=0
connect_36_to=0
dot_28.y=0
dot_28.x=0
dot_xels_8.p=0
dot_28.s=0
dot_28.p=0
dot_24.y=0
dot_24.x=0
dot_xels_4.p=0
dot_24.s=0
dot_20.y=0
dot_24.p=0
dot_20.x=0
dot_20.s=0
dot_20.p=0
dot_27.pixels=0
dot_19.pixels=0
connect_30_to=0
dot_xels_26.p=0
border_x_9=0
border_x_8=0
border_x_7=0
border_x_6=147
dot_xels_22.p=0
border_x_5=352
border_x_4=470
border_x_3=352
border_x_2=147
window_x_16=0
border_x_1=30
window_x_15=0
window_x_14=0
window_x_13=0
connect_26_to=0
window_x_12=0
window_x_11=0
window_x_10=0
window_width=500
dot_17.y=0
dot_36.pixels=0
dot_17.x=0
dot_17.s=0
dot_12.pixels=0
dot_13.y=0
dot_17.p=0
dot_13.x=0
connect_20_to=0
dot_13.s=0
dot_2.pixels=0
dot_13.p=0
dot_7.y=0
dot_7.x=0
dot_xels_19.p=0
dot_7.s=0
dot_3.y=0
dot_7.p=0
dot_3.x=0
connect_7_to=0
connect_16_to=0
dot_xels_15.p=0
dot_3.s=5
dot_3.p=200
dot_xels_11.p=0
connect_37_to=0
dot_38.y=0
dot_38.x=0
dot_21.pixels=0
dot_13.pixels=0
dot_38.s=0
dot_34.y=0
dot_38.p=0
dot_34.x=0
dot_34.s=0
window_background_color=\#FF0096
connect_10_to=0
connect_1_to=2
dot_39.pixels=0
dot_30.y=0
dot_34.p=0
dot_30.x=0
dot_30.s=0
dot_30.p=0
dot_5.pixels=0
connect_31_to=0
dot_xels_36.p=0
dot_xels_32.p=0
window_y_16=0
dot_30.pixels=0
window_y_15=0
window_y_14=0
window_y_13=0
connect_27_to=0
window_y_12=0
window_y_11=0
window_y_10=0
dot_16.pixels=0
dot_27.y=0
dot_27.x=0
dot_xels_7.p=0
dot_27.s=0
dot_6.pixels=0
dot_23.y=0
dot_27.p=0
dot_23.x=0
dot_xels_3.p=0
connect_21_to=0
dot_23.s=0
dot_23.p=0
dot_xels_29.p=0
connect_17_to=0
connect_8_to=0
dot_xels_25.p=0
dot_xels_21.p=0
dot_33.pixels=0
dot_25.pixels=0
connect_38_to=0
connect_11_to=0
connect_2_to=3
dot_40.y=0
dot_40.x=0
dot_16.y=0
dot_16.x=0
dot_40.s=0
dot_9.pixels=0
dot_40.p=0
dot_16.s=0
dot_12.y=0
dot_16.p=0
dot_12.x=0
connect_32_to=0
window_y_9=0
window_y_8=0
window_y_7=0
dot_12.s=0
window_y_6=0
window_y_5=0
window_y_4=0
dot_12.p=0
window_y_3=0
window_y_2=0
dot_6.y=0
window_y_1=1
dot_6.x=0
dot_xels_18.p=0
dot_6.s=0
dot_10.pixels=0
dot_6.p=0
dot_2.y=0
dot_2.x=0
connect_28_to=0
dot_xels_14.p=0
dot_2.s=3
dot_2.p=200
dot_28.pixels=0
dot_xels_10.p=0
dot_37.y=0
dot_37.x=0
dot_37.s=0
dot_37.p=0
dot_33.y=0
dot_33.x=0
connect_22_to=0
dot_33.s=0
dot_33.p=0
dot_xels_39.p=0
connect_18_to=0
connect_9_to=0
dot_37.pixels=0
dot_xels_35.p=0
dot_29.pixels=0
dot_xels_31.p=0
connect_39_to=0
dot_3.pixels=0
connect_3_to=1
connect_12_to=0
dot_26.y=0
dot_26.x=0
dot_xels_6.p=0
dot_26.s=0
dot_26.p=0
dot_22.y=0
dot_22.x=0
connect_33_to=0
dot_xels_2.p=442
dot_22.s=0
dot_22.pixels=0
dot_14.pixels=0
dot_22.p=0
dot_xels_28.p=0
connect_29_to=0
dot_xels_24.p=0
dot_xels_20.p=0
